p8105\_hw6\_jy2944
================
Jie Yu
11/25/2018

-   [Problem 1](#problem-1)
    -   [Import and tidy data](#import-and-tidy-data)
    -   [Fit a logistic regression for one city](#fit-a-logistic-regression-for-one-city)
    -   [Fit logistic regression for each of the cities](#fit-logistic-regression-for-each-of-the-cities)
    -   [Plot showing ORs and CIs for each city](#plot-showing-ors-and-cis-for-each-city)
-   [Problem 2](#problem-2)
    -   [Import and tidy data](#import-and-tidy-data-1)

Problem 1
=========

### Import and tidy data

Read data through a [GitHub repository](https://github.com/washingtonpost/data-homicides). Create a `city_state` variable (e.g. “Baltimore, MD”), and a binary variable indicating whether the homicide is solved. Omit cities Dallas, TX; Phoenix, AZ; and Kansas City, MO – these don’t report victim race. Also omit Tulsa, AL – this is a data entry mistake. Modifiy `victim_race` to have categories `white` and `non-white`, with `white` as the reference category. Be sure that `victim_age` is numeric.

``` r
# Read data through a Github repo
homicide_data = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
  mutate(
    # Create a `city_state` variable (e.g. “Baltimore, MD”)
    city_state = str_c(city, ",", state),
    # Create a binary variable indicating whether the homicide is solved: 1 - solved; 0 - unsolved
    resolved = as.numeric(disposition == "Closed by arrest")
    ) %>% 
  # Omit some cities
  filter(!city_state %in% c("Dallas,TX","Phoenix,AZ", "Kansas City,MO", "Tulsa,AL")) %>%
  mutate(
    # Modifiy `victim_race` to have categories `white` and `non-white`, with `white` as the reference
    victim_race = fct_relevel(ifelse(victim_race == "White", "white", "non-white"), "white"),
    # Be sure that `victim_age` is numeric
    victim_age = as.numeric(victim_age)
    )
```

### Fit a logistic regression for one city

For the city of Baltimore, MD, use the `glm` function to fit a logistic regression with resolved vs unresolved as the outcome and victim age, sex and race (as just defined) as predictors. Save the output of `glm` as an R object; apply the `broom::tidy` to this object; and obtain the estimate and CI of the **adjusted odds ratio** for solving homicides comparing non-white victims to white victims keeping all other variables fixed.

``` r
balti_logistic = homicide_data %>% 
  # filter the city
  filter(city_state == "Baltimore,MD") %>% 
  # Fit a logistic regression: `resolved` as outcome
  glm(resolved ~ victim_age + victim_sex + victim_race, data = ., family = binomial()) 

balti_logistic %>% 
  broom::tidy() %>% 
  # Obtain odds ratio and its CI
  # Note: logistic model estimates are log odds ratios, so we need to tranform them back
  mutate(
    OR = exp(estimate),
    conf.lower = exp(estimate - std.error * 1.96),
    conf.upper = exp(estimate + std.error * 1.96)
    ) %>%
  select(term, OR, conf.lower, conf.upper, p.value) %>% 
  knitr::kable(digits = 3)
```

| term                  |     OR|  conf.lower|  conf.upper|  p.value|
|:----------------------|------:|-----------:|-----------:|--------:|
| (Intercept)           |  3.274|       2.067|       5.186|    0.000|
| victim\_age           |  0.993|       0.987|       0.999|    0.032|
| victim\_sexMale       |  0.412|       0.315|       0.537|    0.000|
| victim\_racenon-white |  0.441|       0.313|       0.620|    0.000|

The odds ratio for solving solving homicides comparing non-white victims to white victims is 0.441 and the CI is (0.312, 0.620) with 95% confidence interval. It means that homicides in which the victim was non-white were substantially less likely to be resolved than those in which the victim was white (OR = 0.441 &lt; 1, p-value &lt; 0.001). The non-white victims had 0.441 times the odds of having their cases being resolved compared to the white victims. The true odd ratio is between 0.312 and 0.620.

### Fit logistic regression for each of the cities

Now run `glm` for each of the cities in the dataset, and extract the adjusted odds ratio and CI for solving homicides comparing non-white victims to white victims. Do this within a “tidy” pipeline, making use of `purrr::map`, list columns, and `unnest` as necessary to create a dataframe with estimated ORs and CIs for each city.

``` r
# Contruct a function `or_and_ci` to calculate OR and CI using `glm` results
or_and_ci = function(df){
    glm = glm(resolved ~ victim_age + victim_sex + victim_race, data = df, family = binomial())
    
    logistic_tidy = glm %>% 
      broom::tidy() %>% 
      mutate(
        OR = exp(estimate),
        conf.lower = exp(estimate - std.error * 1.96),
        conf.upper = exp(estimate + std.error * 1.96)
        ) %>%
      select(term, OR, conf.lower, conf.upper, p.value) %>% 
      # filter the term of non-white victims
      filter(term == "victim_racenon-white") %>% 
      select(-term)
    }

city_logistic = homicide_data %>% 
  # nest the data by each city
  group_by(city_state) %>% 
  nest() %>% 
  # Apply the function `or_and_ci` to each city
  mutate(or_and_ci = map(.x = data, ~or_and_ci(.x))) %>% 
  select(-data) %>% 
  unnest()

city_logistic
## # A tibble: 47 x 5
##    city_state        OR conf.lower conf.upper    p.value
##    <chr>          <dbl>      <dbl>      <dbl>      <dbl>
##  1 Albuquerque,NM 0.741     0.451       1.22  0.238     
##  2 Atlanta,GA     0.753     0.432       1.31  0.317     
##  3 Baltimore,MD   0.441     0.313       0.620 0.00000268
##  4 Baton Rouge,LA 0.668     0.313       1.43  0.296     
##  5 Birmingham,AL  1.04      0.615       1.76  0.886     
##  6 Boston,MA      0.115     0.0472      0.278 0.00000172
##  7 Buffalo,NY     0.390     0.213       0.715 0.00231   
##  8 Charlotte,NC   0.558     0.321       0.969 0.0383    
##  9 Chicago,IL     0.562     0.431       0.733 0.0000207 
## 10 Cincinnati,OH  0.318     0.184       0.551 0.0000428 
## # ... with 37 more rows
```

### Plot showing ORs and CIs for each city

Create a plot that shows the estimated ORs and CIs for each city. Organize cities according to estimated OR, and comment on the plot.

``` r
city_logistic %>% 
  # # organize cities according to estimated OR
  mutate(city_state = forcats::fct_reorder(city_state, OR)) %>% 
  # make the plot
  ggplot(aes(x = city_state, y = OR)) + 
  # points represent the ORs for each city
  geom_point(color = "red") + 
  # geom_errorbar(): add error bars based on the upper and lower limits
  geom_errorbar(aes(x = city_state, ymin = conf.lower, ymax = conf.upper)) + 
  labs(
    title = "Estimated ORs and CIs for solving homicides comparing non-white victims to white victims", 
    x = "City", 
    y = "Estimate odds ratio") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

<img src="p8105_hw6_jy2944_files/figure-markdown_github/p1_plot-1.png" width="90%" />

Estimated odds ratio and its confidence interval for solving homices comparing non-white victioms to white victims varies across cities in US. Most of the cities have estimated odds ratios lower than 1, meaning that homicides in which the victim is non-white are less likely to be resolved than those in which the victim is white in US. Boston, MA has the lowest estimated odds ratio while Tampa, FL has the highest estimated odds ratio.

Problem 2
=========

This problem focuses on the effects of several variables on a child's birthweight.

### Import and tidy data

``` r
birth_weight = read_csv("./data/birthweight.csv") %>%
  janitor::clean_names() %>% 
  mutate(
    # convert some categorical data from integer to factor
    babysex = as.factor(babysex),
    frace = as.factor(frace),
    malform = as.factor(malform),
    mrace = as.factor(mrace),
    # convert birthweight unit from grams to pounds
    bwt = as.numeric(bwt * 0.00220462)
  )

# Check if there is missing data
skimr::skim(birth_weight )
## Skim summary statistics
##  n obs: 4342 
##  n variables: 20 
## 
## -- Variable type:factor ----------------------------------------------------------------------------------------
##  variable missing complete    n n_unique                      top_counts
##   babysex       0     4342 4342        2         1: 2230, 2: 2112, NA: 0
##     frace       0     4342 4342        5 1: 2123, 2: 1911, 4: 248, 3: 46
##   malform       0     4342 4342        2           0: 4327, 1: 15, NA: 0
##     mrace       0     4342 4342        4 1: 2147, 2: 1909, 4: 243, 3: 43
##  ordered
##    FALSE
##    FALSE
##    FALSE
##    FALSE
## 
## -- Variable type:integer ---------------------------------------------------------------------------------------
##  variable missing complete    n     mean    sd  p0 p25 p50 p75 p100
##     bhead       0     4342 4342  33.65    1.62  21  33  34  35   41
##   blength       0     4342 4342  49.75    2.72  20  48  50  51   63
##     delwt       0     4342 4342 145.57   22.21  86 131 143 157  334
##   fincome       0     4342 4342  44.11   25.98   0  25  35  65   96
##  menarche       0     4342 4342  12.51    1.48   0  12  12  13   19
##   mheight       0     4342 4342  63.49    2.66  48  62  63  65   77
##    momage       0     4342 4342  20.3     3.88  12  18  20  22   44
##    parity       0     4342 4342   0.0023  0.1    0   0   0   0    6
##   pnumlbw       0     4342 4342   0       0      0   0   0   0    0
##   pnumsga       0     4342 4342   0       0      0   0   0   0    0
##      ppwt       0     4342 4342 123.49   20.16  70 110 120 134  287
##    wtgain       0     4342 4342  22.08   10.94 -46  15  22  28   89
##      hist
##  ▁▁▁▁▅▇▁▁
##  ▁▁▁▁▁▇▁▁
##  ▁▇▅▁▁▁▁▁
##  ▁▂▇▂▂▂▁▃
##  ▁▁▁▁▂▇▁▁
##  ▁▁▁▅▇▂▁▁
##  ▂▇▅▂▁▁▁▁
##  ▇▁▁▁▁▁▁▁
##  ▁▁▁▇▁▁▁▁
##  ▁▁▁▇▁▁▁▁
##  ▁▇▆▁▁▁▁▁
##  ▁▁▁▇▇▁▁▁
## 
## -- Variable type:numeric ---------------------------------------------------------------------------------------
##  variable missing complete    n  mean   sd    p0   p25   p50   p75  p100
##       bwt       0     4342 4342  6.87 1.13  1.31  6.19  6.91  7.63 10.56
##   gaweeks       0     4342 4342 39.43 3.15 17.7  38.3  39.9  41.1  51.3 
##     ppbmi       0     4342 4342 21.57 3.18 13.07 19.53 21.03 22.91 46.1 
##    smoken       0     4342 4342  4.15 7.41  0     0     0     5    60   
##      hist
##  ▁▁▁▃▇▇▂▁
##  ▁▁▁▁▃▇▁▁
##  ▁▇▅▁▁▁▁▁
##  ▇▁▁▁▁▁▁▁
```

After importing the data, I convert `babysex`, `frace`, `malform` and `mrace` from integer to factor because they are categorical data. I also convert the unit of `bwt` from grams to pounds to make it consistent with other weitht variables in the dataset. There is no missing data in the dataset.

Now, the explanations of each variable are as follows:

-   `babysex`: baby’s sex (male = 1, female = 2)
-   `bhead`: baby’s head circumference at birth (centimeters)
-   `blength`: baby’s length at birth (centimeteres)
-   `bwt`: baby’s birth weight (pounds)
-   `delwt`: mother’s weight at delivery (pounds)
-   `fincome`: family monthly income (in hundreds, rounded)
-   `frace`: father’s race (1= White, 2 = Black, 3 = Asian, 4 = Puerto Rican, 8 = Other, 9 = Unknown)
-   `gaweeks`: gestational age in weeks
-   `malform`: presence of malformations that could affect weight (0 = absent, 1 = present)
-   `menarche`: mother’s age at menarche (years)
-   `mheigth`: mother’s height (inches)
-   `momage`: mother’s age at delivery (years)
-   `mrace`: mother’s race (1= White, 2 = Black, 3 = Asian, 4 = Puerto Rican, 8 = Other)
-   `parity`: number of live births prior to this pregnancy
-   `pnumlbw`: previous number of low birth weight babies
-   `pnumgsa`: number of prior small for gestational age babies
-   `ppbmi`: mother’s pre-pregnancy BMI
-   `ppwt`: mother’s pre-pregnancy weight (pounds)
-   `smoken`: average number of cigarettes smoked per day during pregnancy
-   `wtgain`: mother’s weight gain during pregnancy (pounds)

``` r
library(leaps)
leaps <- regsubsets(bwt ~ ., data = birth_weight)
## Reordering variables and trying again:
summary(leaps)
## Subset selection object
## Call: regsubsets.formula(bwt ~ ., data = birth_weight)
## 24 Variables  (and intercept)
##          Forced in Forced out
## babysex2     FALSE      FALSE
## bhead        FALSE      FALSE
## blength      FALSE      FALSE
## delwt        FALSE      FALSE
## fincome      FALSE      FALSE
## frace2       FALSE      FALSE
## frace3       FALSE      FALSE
## frace4       FALSE      FALSE
## frace8       FALSE      FALSE
## gaweeks      FALSE      FALSE
## malform1     FALSE      FALSE
## menarche     FALSE      FALSE
## mheight      FALSE      FALSE
## momage       FALSE      FALSE
## mrace2       FALSE      FALSE
## mrace3       FALSE      FALSE
## mrace4       FALSE      FALSE
## parity       FALSE      FALSE
## ppbmi        FALSE      FALSE
## ppwt         FALSE      FALSE
## smoken       FALSE      FALSE
## pnumlbw      FALSE      FALSE
## pnumsga      FALSE      FALSE
## wtgain       FALSE      FALSE
## 1 subsets of each size up to 9
## Selection Algorithm: exhaustive
##          babysex2 bhead blength delwt fincome frace2 frace3 frace4 frace8
## 1  ( 1 ) " "      "*"   " "     " "   " "     " "    " "    " "    " "   
## 2  ( 1 ) " "      "*"   "*"     " "   " "     " "    " "    " "    " "   
## 3  ( 1 ) " "      "*"   "*"     " "   " "     " "    " "    " "    " "   
## 4  ( 1 ) " "      "*"   "*"     "*"   " "     " "    " "    " "    " "   
## 5  ( 1 ) " "      "*"   "*"     "*"   " "     " "    " "    " "    " "   
## 6  ( 1 ) " "      "*"   "*"     "*"   " "     " "    " "    " "    " "   
## 7  ( 1 ) " "      "*"   "*"     "*"   " "     " "    " "    " "    " "   
## 8  ( 1 ) " "      "*"   "*"     "*"   " "     " "    " "    "*"    " "   
## 9  ( 1 ) "*"      "*"   "*"     "*"   " "     " "    " "    "*"    " "   
##          gaweeks malform1 menarche mheight momage mrace2 mrace3 mrace4
## 1  ( 1 ) " "     " "      " "      " "     " "    " "    " "    " "   
## 2  ( 1 ) " "     " "      " "      " "     " "    " "    " "    " "   
## 3  ( 1 ) " "     " "      " "      " "     " "    "*"    " "    " "   
## 4  ( 1 ) " "     " "      " "      " "     " "    "*"    " "    " "   
## 5  ( 1 ) "*"     " "      " "      " "     " "    "*"    " "    " "   
## 6  ( 1 ) "*"     " "      " "      " "     " "    "*"    " "    " "   
## 7  ( 1 ) "*"     " "      " "      " "     " "    "*"    " "    " "   
## 8  ( 1 ) "*"     " "      " "      " "     " "    "*"    " "    " "   
## 9  ( 1 ) "*"     " "      " "      " "     " "    "*"    " "    " "   
##          parity pnumlbw pnumsga ppbmi ppwt smoken wtgain
## 1  ( 1 ) " "    " "     " "     " "   " "  " "    " "   
## 2  ( 1 ) " "    " "     " "     " "   " "  " "    " "   
## 3  ( 1 ) " "    " "     " "     " "   " "  " "    " "   
## 4  ( 1 ) " "    " "     " "     " "   " "  " "    " "   
## 5  ( 1 ) " "    " "     " "     " "   " "  " "    " "   
## 6  ( 1 ) " "    " "     " "     " "   " "  "*"    " "   
## 7  ( 1 ) " "    " "     " "     "*"   " "  "*"    " "   
## 8  ( 1 ) " "    " "     " "     "*"   " "  "*"    " "   
## 9  ( 1 ) " "    " "     " "     "*"   " "  "*"    " "
plot(leaps, scale = "bic")
```

<img src="p8105_hw6_jy2944_files/figure-markdown_github/unnamed-chunk-2-1.png" width="90%" />
